name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.10
  - pip
  - cudatoolkit=11.3
  - pytorch
  - torchvision
  - numpy
  - xformers/label/dev::xformers
  - pip:
    - basicsr
    - diffusers
    - fairscale==0.4.4
    - fonts
    - font-roboto
    - gfpgan
    - gradio==3.4b3
    - invisible-watermark
    - numpy
    - omegaconf==2.2.3
    - piexif
    - Pillow
    - pytorch_lightning==1.7.7
    - realesrgan
    - scikit-image>=0.19
    - timm==0.4.12
    - transformers==4.21.2
    - einops==0.4.1
    - jsonmerge
    - clean-fid
    - resize-right
    - torchdiffeq
    - kornia==0.6.7
    - lark
    - functorch
    - jupyterlab
    - ipywidgets
    - jupyter-archive
    - GitPython
    - inflection
    - accelerate
    - ftfy
    - matplotlib
    - timm
    - torchdiffeq
    - torchmetrics==0.9.3
    - torchtext==0.13.1
    - numexpr
