name: ldm
channels:
  - nvidia/label/cuda-11.6.2
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.10
  - pip
  - cudatoolkit
  - pytorch=1.12.1
  - torchvision
  - numpy
  - xformers/label/dev::xformers
  - pip:
    - accelerate==0.12.0
    - albumentations==1.3.0
    - basicsr==1.4.2
    - bitsandbytes==0.35.0
    - blendmodes==2022
    - clean-fid==0.1.29
    - diffusers[torch]==0.10.0
    - einops==0.4.1
    - fairscale==0.4.9
    - font-roboto
    - fonts
    - ftfy==6.1.1
    - functorch
    - gdown
    - gfpgan==1.3.8
    - git+https://github.com/openai/CLIP.git
    - GitPython==3.1.27
    - gradio==3.15.0
    - inflection==0.5.1
    - invisible-watermark
    - ipywidgets
    - jsonmerge==1.8.0
    - jupyter-archive
    - jupyterlab
    - kornia==0.6.7
    - lark==1.1.2
    - modelcards==0.1.6
    - omegaconf==2.2.3
    - open_clip_torch
    - opencv-contrib-python
    - piexif==1.1.3
    - Pillow==9.4.0
    - psutil
    - pytorch_lightning==1.7.6
    - realesrgan==0.3.0
    - requests
    - resize-right==0.0.2
    - safetensors==0.2.7
    - scikit-image>=0.19.2
    - tensorboard==2.11.0
    - timm==0.6.7
    - torchdiffeq==0.2.3
    - torchsde==0.2.5
    - tqdm
    - transformers==4.19.2
