name: ldm
channels:
  - nvidia/label/cuda-11.6.2
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.10
  - pip
  - cudatoolkit
  - pytorch=1.12.1
  - torchvision
  - numpy
  - xformers/label/dev::xformers
  - pip:
    - gdown
    - accelerate
    - clip
    - torchsde
    - basicsr
    - diffusers[torch]==0.10.0 
    - fairscale
    - fonts
    - font-roboto
    - invisible-watermark
    - numpy
    - omegaconf
    - piexif
    - Pillow
    - pytorch_lightning==1.7.7
    - realesrgan
    - scikit-image>=0.19
    - timm==0.4.12
    - transformers==4.25.1
    - einops
    - jsonmerge
    - clean-fid
    - resize-right
    - torchdiffeq
    - kornia
    - lark
    - functorch
    - jupyterlab
    - ipywidgets
    - jupyter-archive
    - GitPython
    - inflection
    - albumentations==1.3.0
    - bitsandbytes==0.35.0
    - font-roboto
    - fonts
    - ftfy==6.1.1
    - gfpgan==1.3.8
    - gradio==3.9
    - modelcards==0.1.6
    - tensorboard==2.11.0
    - tqdm    
    - open_clip_torch
    - safetensors 
